import {
  Sunrise, FileSearch, MessagesSquare, HeartPulse, ListChecks, Route, Swords,
  Receipt, Radar, Scale, Users, ShieldAlert, TrendingUp, Plane, FileWarning,
  Home, Landmark, Building2, Siren, Archive, Contact, PenTool, Lock,
} from 'lucide-react';
import type { AgentModule } from '@/types';

/**
 * The full ZYRON module register. This is the single source of truth for the
 * marketing site, the console router and the architecture diagram — add a
 * module here and it appears everywhere.
 */
export const MODULES: AgentModule[] = [
  {
    id: 1, code: 'BRF', name: 'Your Morning Briefing', tagline: 'Your day, decided before you wake',
    functionality: 'One synthesised morning sync across mail, calendar, tasks and biometrics.',
    execution: 'Reads overnight mail, resolves calendar collisions, then places deep-work blocks inside your measured peak-energy window.',
    inputs: ['Calendar', 'Mail', 'Tasks', 'Sleep data'],
    action: 'Delivers an audio and text sync at wake time',
    benefit: 'You start the day already oriented',
    tier: 'core', risk: 'autonomous', icon: Sunrise,
  },
  {
    id: 2, code: 'DSR', name: 'Meeting Prep', tagline: 'Walk in knowing everything',
    functionality: 'A one-page dossier fifteen minutes before every meeting.',
    execution: 'Pulls the agenda, the thread history, past decisions with this counterpart and the relevant drive files into a single briefing.',
    inputs: ['Drive', 'Mail threads', 'Chat logs', 'Decision log'],
    action: 'Files a pre-meeting dossier to your device',
    benefit: 'Zero searching, full recall',
    tier: 'core', risk: 'autonomous', icon: FileSearch,
  },
  {
    id: 3, code: 'CMS', name: 'Message Handler', tagline: 'Speaks in your voice, waits for your nod',
    functionality: 'Handles WhatsApp, email and voice notes end to end.',
    execution: 'Transcribes voice notes, checks your calendar before replying to a scheduling request, and queues the finished draft for one-tap dispatch.',
    inputs: ['WhatsApp API', 'Voice notes', 'Mail'],
    action: 'Drafts and dispatches on approval',
    benefit: 'Inbox stops being a job',
    tier: 'core', risk: 'approval', icon: MessagesSquare,
  },
  {
    id: 4, code: 'BIO', name: 'Burnout Guard', tagline: 'Stops you working yourself into the ground',
    functionality: 'Balances workload against what your body can actually carry.',
    execution: 'Watches HRV, sleep debt and meeting density. After four unbroken hours it blocks a recovery buffer and demotes low-priority work.',
    inputs: ['Wearable', 'HRV', 'Sleep cycles'],
    action: 'Blocks recovery buffers, defers low-value work',
    benefit: 'Output stays high without the crash',
    tier: 'core', risk: 'autonomous', icon: HeartPulse,
  },
  {
    id: 5, code: 'CLT', name: 'Promise Tracker', tagline: 'Every promise, tracked to done',
    functionality: 'Extracts commitments from anything you say or write.',
    execution: 'Detects lines like "I will send the deck by Tuesday", files them with an owner and a date, then runs the follow-up sequence itself.',
    inputs: ['Mail', 'Meeting notes', 'Voice logs'],
    action: 'Extracts commitments and closes the loop',
    benefit: 'Nothing you promised gets dropped',
    tier: 'core', risk: 'autonomous', icon: ListChecks,
  },
  {
    id: 6, code: 'PSG', name: 'Schedule Protector', tagline: 'Moves the day before it breaks',
    functionality: 'Live traffic, transit and overrun awareness across the calendar.',
    execution: 'When the gap between a physical and a virtual meeting collapses, it drafts the shift message before you notice the problem.',
    inputs: ['Location', 'Traffic', 'Calendar'],
    action: 'Reschedules and notifies ahead of the conflict',
    benefit: 'You are never the one who is late',
    tier: 'core', risk: 'approval', icon: Route,
  },
  {
    id: 7, code: 'NEG', name: 'Negotiation Practice', tagline: 'Lose the rehearsal, win the room',
    functionality: 'A sparring counterparty for deals, raises and disputes.',
    execution: 'Adopts the other side\'s persona from what it knows of them, runs the mock exchange, then names your weak lines and the pressure points you missed.',
    inputs: ['Counterparty profile', 'Deal terms'],
    action: 'Runs adversarial rehearsal with tactical debrief',
    benefit: 'You arrive already tested',
    tier: 'core', risk: 'autonomous', icon: Swords,
  },
  {
    id: 8, code: 'FIN', name: 'Money Leak Finder', tagline: 'Finds the money quietly leaving',
    functionality: 'Continuous audit of invoices, receipts and recurring charges.',
    execution: 'OCRs receipts, matches them against statements, and flags duplicate billing, idle subscriptions and silent price rises with a cancellation ready to send.',
    inputs: ['Receipts', 'Invoices', 'Card feeds'],
    action: 'Flags leaks and stages cancellations',
    benefit: 'Recovers spend you forgot about',
    tier: 'core', risk: 'approval', icon: Receipt,
  },
  {
    id: 9, code: 'REP', name: 'Online Reputation Watch', tagline: 'Spots bad press before it spreads',
    functionality: 'Watches mentions, reviews and press about you and your company.',
    execution: 'Monitors news APIs and social listening. On a negative sentiment spike it prepares a response and escalates it; on a positive one it suggests amplification.',
    inputs: ['News APIs', 'Social mentions', 'Review sites'],
    action: 'Detects sentiment shifts and drafts the reply',
    benefit: 'You respond in minutes, not days',
    tier: 'extended', risk: 'approval', icon: Radar,
  },
  {
    id: 10, code: 'DJB', name: 'Decision Journal', tagline: 'Shows you the mistakes you keep repeating',
    functionality: 'Logs major decisions with the reasoning behind them.',
    execution: 'Captures the rationale at the moment of decision, then reopens it at 30, 60 and 90 days to compare intent against outcome and surface repeat biases.',
    inputs: ['Voice notes', 'Chat logs', 'Outcomes'],
    action: 'Runs timed outcome reviews and names your patterns',
    benefit: 'The same mistake stops repeating',
    tier: 'extended', risk: 'autonomous', icon: Scale,
  },
  {
    id: 11, code: 'DEL', name: 'Team Follow-Up', tagline: 'Holds the team to the date',
    functionality: 'Tracks what you handed off, not only what you took on.',
    execution: 'Reads "I\'ll assign this to Sara" out of a thread, builds the delegation record and nudges the assignee before the deadline lands.',
    inputs: ['Mail', 'Chat', 'Task boards'],
    action: 'Nudges assignees ahead of the due date',
    benefit: 'You stop being the reminder service',
    tier: 'extended', risk: 'approval', icon: Users,
  },
  {
    id: 12, code: 'CNT', name: 'Emergency Handover', tagline: 'If you go quiet, the business does not',
    functionality: 'A dead-man\'s switch for your operational knowledge.',
    execution: 'After a configured silence it checks in across call, SMS and WhatsApp. With no answer it releases an encrypted package — pending approvals, live deals, key contacts — to your named trustee.',
    inputs: ['Interaction telemetry', 'Trustee registry'],
    action: 'Escalates, then releases the sealed package',
    benefit: 'Continuity survives the worst day',
    tier: 'extended', risk: 'sealed', icon: ShieldAlert,
  },
  {
    id: 13, code: 'ROI', name: 'Agent Report Card', tagline: 'Proves whether its advice actually helped',
    functionality: 'Audits the outcome of every recommendation ZYRON has made.',
    execution: 'Follows each suggestion — reject the deal, cancel the tool, take the meeting — to its result and reports acceptance rate, hours reclaimed and capital saved monthly.',
    inputs: ['Agent decision log', 'Financials', 'Calendar'],
    action: 'Publishes a monthly self-audit',
    benefit: 'Trust becomes measurable',
    tier: 'extended', risk: 'autonomous', icon: TrendingUp,
  },
  {
    id: 14, code: 'TRV', name: 'Travel Manager', tagline: 'Re-plans while you are still boarding',
    functionality: 'The whole travel chain, from confirmation mail to ground transport.',
    execution: 'Parses bookings into one itinerary. On a delay it holds alternate flights, shifts the hotel window, moves the pickup and files the claim.',
    inputs: ['Booking mail', 'Flight APIs', 'Passport records'],
    action: 'Reroutes logistics and files disruption claims',
    benefit: 'Travel days stop costing you a day',
    tier: 'extended', risk: 'approval', icon: Plane,
  },
  {
    id: 15, code: 'DOC', name: 'Contract Checker', tagline: 'Reads the clause you would skim',
    functionality: 'Plain-language risk analysis of any agreement you forward it.',
    execution: 'Flags non-standard termination windows, liability exposure, auto-renewal traps, and tracks every expiry date it finds.',
    inputs: ['Uploaded PDFs', 'Signed agreements'],
    action: 'Flags risk clauses and tracks renewals',
    benefit: 'You sign knowing what you signed',
    tier: 'extended', risk: 'autonomous', icon: FileWarning,
  },
  {
    id: 16, code: 'HHM', name: 'Home & Bills Manager', tagline: 'The other job, handled',
    functionality: 'Runs the domestic operating load alongside the professional one.',
    execution: 'Tracks utility due dates, school and clinic schedules, service intervals for the car and the AC, and predicts replenishment from consumption patterns.',
    inputs: ['Bills', 'Family calendar', 'Purchase history'],
    action: 'Auto-reminders, pay approvals, predictive restock',
    benefit: 'Home stops leaking attention',
    tier: 'extended', risk: 'approval', icon: Home,
  },
  {
    id: 17, code: 'CMP', name: 'Tax & Deadline Alerts', tagline: 'Deadlines that carry penalties',
    functionality: 'Tax, licensing and certification dates with escalating alerts.',
    execution: 'Maintains the filing calendar and the document checklist your accountant will ask for, warning at two weeks and again at three days.',
    inputs: ['Regulatory calendars', 'Licence registry'],
    action: 'Escalates until the filing is confirmed',
    benefit: 'No penalty ever arrives by surprise',
    tier: 'extended', risk: 'autonomous', icon: Landmark,
  },
  {
    id: 18, code: 'PRP', name: 'Rent & Property Tracker', tagline: 'Passive assets, actively watched',
    functionality: 'Monitoring for rentals and property holdings.',
    execution: 'Tracks rent cycles and sends the tenant reminder on your approval, keeps the property tax and utility schedule, and summarises local rate movement.',
    inputs: ['Rent schedule', 'Tax calendar', 'Listing data'],
    action: 'Tenant reminders and market summaries',
    benefit: 'The portfolio runs without you',
    tier: 'extended', risk: 'approval', icon: Building2,
  },
  {
    id: 19, code: 'CRS', name: 'Emergency Mode', tagline: 'One command, everyone who matters is told',
    functionality: 'Stakeholder mobilisation for the moment things break.',
    execution: 'On the trigger phrase it stages pre-approved messages for counsel, PR and family, gathers the relevant documents in one place, and leaves you only the approve-or-edit decision.',
    inputs: ['Trigger phrase', 'Stakeholder registry'],
    action: 'Stages messaging and centralises documents',
    benefit: 'Cognitive load drops when it matters most',
    tier: 'extended', risk: 'sealed', icon: Siren,
  },
  {
    id: 20, code: 'LGY', name: 'Personal Memory Vault', tagline: 'What you would want remembered',
    functionality: 'A private archive of thinking, voice and turning points.',
    execution: 'Compiles conversations, decisions and recordings into an encrypted personal archive, releasable to family on your terms.',
    inputs: ['Voice memories', 'Decision history'],
    action: 'Compiles the sealed personal archive',
    benefit: 'A record worth inheriting',
    tier: 'signature', risk: 'sealed', icon: Archive,
  },
  {
    id: 21, code: 'VIP', name: 'People & Birthdays', tagline: 'Remembers what people care about',
    functionality: 'A living profile for every person who matters.',
    execution: 'Holds preferences, milestones and history, then prompts you before the meeting and suggests the message or gift that actually fits.',
    inputs: ['Contacts', 'Interaction history', 'Milestones'],
    action: 'Pre-meeting recall and thoughtful prompts',
    benefit: 'Relationships stop decaying by neglect',
    tier: 'signature', risk: 'autonomous', icon: Contact,
  },
  {
    id: 22, code: 'BRD', name: 'Your Writing Voice', tagline: 'One voice, everywhere',
    functionality: 'Keeps public and professional output sounding like you.',
    execution: 'Learns your register from your own archive and flags outgoing posts, statements and mail that drift from it before they ship.',
    inputs: ['Public posts', 'Sent mail', 'Style corpus'],
    action: 'Flags off-voice content pre-publication',
    benefit: 'A consistent, deliberate public identity',
    tier: 'signature', risk: 'approval', icon: PenTool,
  },
  {
    id: 23, code: 'PRV', name: 'Privacy & Your Data', tagline: 'Your data stays yours — enforced, not promised',
    functionality: 'Your data stays yours — enforced, not promised.',
    execution: 'On-device processing wherever possible, end-to-end encryption elsewhere, a full audit trail of every access, and a standing delete-everything command.',
    inputs: ['All data streams'],
    action: 'Encrypts, audits and honours deletion instantly',
    benefit: 'Trust with a mechanism behind it',
    tier: 'signature', risk: 'sealed', icon: Lock,
  },
];

export const TIERS: Record<string, { label: string; blurb: string }> = {
  core: { label: 'Core operations', blurb: 'The eight modules that run every single day.' },
  extended: { label: 'Extended command', blurb: 'Depth across reputation, legal, logistics and continuity.' },
  signature: { label: 'Signature layer', blurb: 'The personal and sovereign edge of the system.' },
};

export const getModule = (code: string) => MODULES.find((m) => m.code === code);
